description = "Generate a clear and informative architectural document that represents the structure and components of the codebase, based on its actual structure and dependencies."

prompt = """
---
description: Generate a clear and informative architectural document that represents the structure and components of the codebase, based on its actual structure and dependencies.
---

**Objective:** Generate a clear and informative architectural document that represents the structure and components of the codebase, based on its actual structure and dependencies.

**Instructions:**

1. **Analyze the codebase:**  Examine the directory structure, modules, classes, and their relationships to understand the system's architecture. 
2. **Identify key components:** Determine the major building blocks of the system, such as:
    * User Interface components
    * APIs or services
    * Databases
    * External systems
    * Business logic modules
3. **Determine relationships:** Analyze how these components interact with each other. For example:
    * Which modules depend on others?
    * How do data flows between components?
    * What are the communication protocols used?
4. **Determine their structure and purpose:** Understand why the different components are there. For example:
    * What is the purpose of the different components, modules and classes?
    * What are the key methods and functions?
5. **Assemble the architecture document:** Summarize all findings into a well-structured document
    * Structure the document into chapters
    * Progress top-down - from overall description of the architecture down to individual components and modules and finally to classes, methods and functions 

**Expected Output:** A markdown document representation of the codebase's architecture and code. The document should be: 

* **Accurate:** It should correctly reflect the actual structure and dependencies in the codebase.
* **Clear and Concise:** Avoid clutter and use concise explanations for easy understanding.
* **Informative:** The document should convey the key architectural elements and their interactions effectively.  
"""